package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"net/textproto"
	"os"
	"strings"
)

func Init() {
	bs := strings.NewReader(`{
    "needCode": false,
    "hideUserApiKey": false,
    "disableGPT4": false,
    "hideBalanceQuery": true,
    "disableFastLink": false,
    "customModels": "-all,+Plugins=插件专用(Plugins),+ChatGPT-3.5-问答模型=ChatGPT-3.5-问答模型,+ChatGPT-4o-对话(限时免费)=ChatGPT-4o-首选,+ChatGPT-4o-接口2(免费)=GPT-4o-饱和换其他模型,+ChatGPT-4o-mini-接口2(免费)=GPT-4o-mini-饱和换其他模型,+Claude-3-5-sonnet(限时免费)=Claude-3-5-sonnet/慢速,+Grok-Beta(免费)=Grok-Beta(马斯克发布),+ChatGPT-4o-08-06-逆向(免费)=GPT-4o-0806-逆向,+ChatGPT-4o-mini-逆向(免费)=GPT-4o-mini-逆向,+通义千问-图像对话-VL(限时免费)=阿里通义千问-图文问答,+ChatGPT-4o-mini接口4(免费)=ChatGPT-4o-mini&渠道三,+Claude-3-haiku-接口4(免费)=Claude-3-haiku&渠道三,+零一万物-lightning(免费)=零一万物大模型,+腾讯混元Lite(限时免费)=腾讯混元Lite,+Gemini-Pro(限时免费)=Google-Gemini-Pro,+讯飞星火大模型(限时免费)=科大讯飞星火-4,+豆包-Lite-128k(限时免费)=豆包-Lite-128k,+PPT生成助手=PPT大纲生成助手,+抖音热点插件=抖音热点热榜查看,+网易云插件=网易云热歌榜音乐随机播放,+词云图片生成插件=词云图片生成助手,+联网爬虫Search插件=全网资源查找助手,+视频图集去水印插件=聚合去水印-图集/视频,+网页爬虫插件=网页/PDF在线文档阅读助手,+支付宝语音合成插件=支付宝到账语音合成,+战区查询插件=王者低分战区查询助手,+图表生成插件=折线&柱状动态图表生成,+DeepSeek-Coder-V2-Instruct(限时免费)=DeepSeek-V2,+Qwen2-Math-72B-Instruct(限时免费)=阿里通义千问Math,+每日60秒读懂世界插件=每日60秒读懂世界,+智谱清言GLM-4(限时免费)=智谱清言GLM-4,+Stable Definition绘画(限时免费)=Stable Definition绘画,+问答搜索助手插件(限时免费)=ChatGPT联网问答,+Moonshot-8k(限时免费)=Moonshot-8k,+文心一言(限时免费)=百度-文心一言,+百度题库搜题插件=大学生全网题库搜索,+网友的树洞查询TOOL=树洞查询TOOL,+网友的漂流瓶查询TOOL=漂流瓶查询TOOL,+世界未解之谜查询TOOL=世界未解之谜查询TOOL,+文档解析工具TOOl=文档解析工具TOOl,+Word文档生成插件=Word文档生成插件,+腾讯混元(默认)=腾讯混元(默认)",
    "defaultModel": ""
}`)
	req, err := http.NewRequest(http.MethodPost, "https://ai1.yjie.fun/api/config", bs)
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	req.Header.Add("Host", "ai1.yjie.fun")
	req.Header.Add("Origin", "https://ai1.yjie.fun")
	req.Header.Add("Referer", "https://ai1.yjie.fun/?ref=ccbaohe.com")
	req.Header.Add("authorization", "Bearer sk-rmkNimoGp5tjFzm3PCR9QxwajCZza2wF1274xWMRks4U")
	req.Header.Add("content-type", "application/json")
	httpClient := http.Client{}
	resp, err := httpClient.Do(req)
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	resp.Body.Close()
}

var (
	longQuest bool
)

func init() {
	flag.BoolVar(&longQuest, "l", false, "进入上下文对话模式")
	flag.Parse()
}

func Filter[S ~[]E, E any](data S, callback func(E) bool) []E {
	var result []E
	for _, v := range data {
		if callback(v) {
			result = append(result, v)
		}
	}
	return result
}

func main() {
	go Init()
	if longQuest {
		fmt.Println("进入上下文对话模式")
		args := Filter(os.Args[1:], func(item string) bool {
			return item != "-l"
		})
		_ = LongChat(args...)
	}
	if len(os.Args) > 1 {
		_ = chatGPT([]Message{{Role: "user", Content: strings.Join(os.Args[1:], " ")}}, os.Stdout)
		fmt.Println("")
	} else {
		fmt.Println("例子: ai hi 或者 ai -l 进入上下文对话模式")
	}
}

func LongChat(msg ...string) error {
	msgs := []Message{}
	for {
		fmt.Println("---------------------------")
		var (
			text string
			err  error
		)
		if len(msg) > 0 {
			text = strings.Join(msg, " ")
			fmt.Println(text)
			msg = nil
		} else {
			text, err = ReadText()
			if err != nil {
				return err
			}
		}
		msgs = append(msgs, Message{
			Role:    "user",
			Content: text,
		})
		buf := bytes.NewBuffer(nil)
		_ = chatGPT(msgs, &Writer{buf})
		msgs = append(msgs, Message{
			Role:    "assistant",
			Content: buf.String(),
		})
		fmt.Println("")
	}
}

func chatGPT(msg []Message, output io.Writer) error {
	type AutoGenerated struct {
		Messages         []Message `json:"messages"`
		Stream           bool      `json:"stream"`
		Model            string    `json:"model"`
		Temperature      float64   `json:"temperature"`
		PresencePenalty  int       `json:"presence_penalty"`
		FrequencyPenalty int       `json:"frequency_penalty"`
		TopP             float64   `json:"top_p"`
	}
	type AutoGenerated2 struct {
		ID      string `json:"id"`
		Object  string `json:"object"`
		Created int    `json:"created"`
		Model   string `json:"model"`
		Choices []struct {
			Index int `json:"index"`
			Delta struct {
				Content string `json:"content"`
			} `json:"delta"`
			Logprobs     any `json:"logprobs"`
			FinishReason any `json:"finish_reason"`
		} `json:"choices"`
		SystemFingerprint string `json:"system_fingerprint"`
	}
	data := AutoGenerated{
		Messages:         msg,
		Stream:           true,
		Model:            "ChatGPT-4o-mini接口4(免费)",
		Temperature:      0.5,
		PresencePenalty:  0,
		FrequencyPenalty: 0,
		TopP:             1,
	}
	bs, _ := json.Marshal(data)
	urlPath := `https://newapi.yjie.fun/v1/chat/completions`
	req, err := http.NewRequest(http.MethodPost, urlPath, bytes.NewReader(bs))
	if err != nil {
		return err
	}
	req.Header.Add("Host", "newapi.yjie.fun")
	req.Header.Add("authorization", "Bearer sk-rmkNimoGp5tjFzm3PCR9QxwajCZza2wF1274xWMRks4U")
	req.Header.Add("content-type", "application/json")
	req.Header.Set("Accept", "text/event-stream")
	httpClient := http.Client{}
	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	scanner := bufio.NewScanner(resp.Body)
	for scanner.Scan() {
		line := scanner.Bytes()
		if bytes.HasPrefix(line, []byte("data: ")) {
			line = bytes.TrimPrefix(line, []byte("data: "))
			line = bytes.TrimSpace(line)
			var mp AutoGenerated2
			err = json.Unmarshal(line, &mp)
			if err != nil {
				break
			}
			_, err := output.Write([]byte(mp.Choices[0].Delta.Content))
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func ReadText() (string, error) {
	rd := textproto.NewReader(bufio.NewReader(os.Stdin))
	return rd.ReadLine()
}

type Writer struct {
	w io.Writer
}

func (w *Writer) Write(p []byte) (n int, err error) {
	if w.w != nil {
		_, _ = w.w.Write(p)
	}
	return os.Stdout.Write(p)
}

type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}
